volumes:
  database:
  kea4-var:

services:
  kea4:
    image: kea:3.0.2
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - type: bind
        source: ./kea-dhcp4.conf
        target: /etc/kea/kea-dhcp4.conf
    networks:
      ipvlan_network:
        ipv4_address: 10.110.118.5
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - type: bind
        source: ./initdb  #database setup script from kea for first run
        target: /docker-entrypoint-initdb.d
    networks:
      ipvlan_network:
        ipv4_address: 10.110.118.7

networks:
  ipvlan_network:
    driver: ipvlan
    driver_opts:
      parent: enp1s0
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: 10.110.118.0/24
          gateway: 10.110.118.1

